services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: os-report-backend
    volumes:
      - ./backend:/app:delegated
      - ./backend/data:/app/data:rw
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - HOST=0.0.0.0
      - PORT=8000
      - API_PREFIX=/api
      - CORS_ORIGINS=http://localhost:3000
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=DEBUG
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: os-report-frontend
    volumes:
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

# Remover este volume "fantasma" que não está sendo usado
# volumes:
#   db-volume:
#     driver: local 