version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: os-report-backend
    volumes:
      - ./backend:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - HOST=0.0.0.0
      - PORT=8000
      - API_PREFIX=/api
      - CORS_ORIGINS=http://localhost:3000
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: os-report-frontend
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: always

volumes:
  data:
    driver: local 