services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: os-report-backend
    volumes:
      - ./backend:/app:delegated
      - ./backend/data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - HOST=0.0.0.0
      - PORT=8000
      - API_PREFIX=/api
      - CORS_ORIGINS=http://localhost:3000
      - PYTHONUNBUFFERED=1
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    user: "1000:1000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: os-report-frontend
    volumes:
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    restart: always

volumes:
  db-volume:
    driver: local 