FROM node:16-alpine

WORKDIR /app

# Copiar os arquivos de configuração do package.json
COPY package.json package-lock.json ./

# Instalar dependências
RUN npm ci

# Copiar o resto do código fonte
COPY . .

# Expor a porta que o servidor do React vai utilizar
EXPOSE 3000

# Iniciar o servidor de desenvolvimento
CMD ["npm", "start"] 