FROM node:16-alpine

WORKDIR /app

# Copiar os arquivos de configuração do package.json
COPY package.json package-lock.json ./

# Instalar dependências usando "npm install" em vez de "npm ci"
# para resolver problemas de incompatibilidade entre package.json e package-lock.json
RUN npm install

# Copiar o resto do código fonte
COPY . .

# Expor a porta que o servidor do React vai utilizar
EXPOSE 3000

# Iniciar o servidor de desenvolvimento
CMD ["npm", "start"] 