services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistema-manutencao
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - FAST_REFRESH=false
    stdin_open: true
    tty: true
    restart: unless-stopped 