services:
  app:
    build: .
    container_name: sistema-manutencao
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - BROWSER=none
      - WDS_SOCKET_PORT=3000
    stdin_open: true
    tty: true
    restart: on-failure
    command: >
      sh -c "cd /app && npm start" 