FROM python:3.9-slim

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

# Criar diretório de dados
RUN mkdir -p /app/data

EXPOSE 5000

# Comando para iniciar o FastAPI com Uvicorn
CMD ["uvicorn", "run:app", "--host", "0.0.0.0", "--port", "5000"] 